# ~/.config/hypr/hyprpaper.conf

wallpaper {
    monitor = eDP-1
    path = /home/nu11/dotfiles/wallpapers/wp1.jpg
    fit_mode = cover
}

# Optional: Disable the text splash at the bottom
splash = true
